# Generated by Django 3.2 on 2021-04-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0004_auto_20210416_1609'),
        ('timelyapp', '0029_auto_20210405_1351'),
    ]

    operations = [
    ]
