# Generated by Django 3.2 on 2021-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelyapp', '0030_merge_0004_auto_20210416_1609_0029_auto_20210405_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='timelyapp.invoice'),
        ),
    ]
